use_frameworks!
platform :ios, '8.0'

target 'ViperStackSwift_Example' do
  pod 'Swinject', '~> 2.4'
  pod 'SnapKit', '~> 4.0'

  pod 'ViperStackSwift', :path => '../'

  target 'ViperStackSwift_Tests' do
    inherit! :search_paths

    
  end
end
